// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYep-T7neXCMtk5UzNb6UP-EkS9hqas5c',
    appId: '1:966658393290:web:e727be1ae9e02c19c52033',
    messagingSenderId: '966658393290',
    projectId: 'tictactoe-5a4ce',
    authDomain: 'tictactoe-5a4ce.firebaseapp.com',
    storageBucket: 'tictactoe-5a4ce.appspot.com',
    measurementId: 'G-HXSMVZN8V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDofeZIRrb1UTnKpWc_SbMyk0ZVqkxJOUg',
    appId: '1:966658393290:android:cae41e1787dd65e3c52033',
    messagingSenderId: '966658393290',
    projectId: 'tictactoe-5a4ce',
    storageBucket: 'tictactoe-5a4ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh5-1mwa9tNvjLVoqtvCT8A-PYF69ySic',
    appId: '1:966658393290:ios:d05610d643bac79fc52033',
    messagingSenderId: '966658393290',
    projectId: 'tictactoe-5a4ce',
    storageBucket: 'tictactoe-5a4ce.appspot.com',
    iosClientId: '966658393290-mp8bje6s7tgmo1lpa1qr0l9hqivpu8pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tictactoefir',
  );
}
